### ISSUE TITLE
Tasks added to suspended TaskQueue won't run

### ISSUE THREAD

**Issue by RaimarT** [arikis/Overdrive#12]
**Overdrive:** 0.2.2
**Package manager (SPM, Carthage, CocoaPods, Manual):** CocoaPods
**Xcode:** 8.2.1
**Platform:** iOS 10

Tasks added to a TaskQueue being suspended don't run after setting `isSuspended = false`. Seems to be a Task specific issue because adding a BlockOperation to the TaskQueue's internal OperationQueue does not cause this issue. Please notice the attached sample code.
[ViewController.swift.zip](https://github.com/arikis/Overdrive/files/783112/ViewController.swift.zip)

**Comment by arikis** [comment]
Fixed in [`2286c23efa5861376cc0e79d203c47d2311df331`](https://github.com/arikis/Overdrive/commit/2286c23efa5861376cc0e79d203c47d2311df331)
