### ISSUE TITLE
Release with the memory leak fixed?

### ISSUE THREAD

**Issue by biocross** [arikis/Overdrive#16]
**Overdrive:** `0.2.2`
**Package manager (SPM, Carthage, CocoaPods, Manual):** `CocoaPods`
**Xcode:** `8.3.1`
**Platform:** `iOS`

Hi @arikis, 

The project I'm working on requires Overdrive to work, and while I know I'm not supposed to be asking for ETAs around here, I wanted to know if we can just release a minor bumped version of Overdrive (maybe 0.2.3) with mainly the [task observer memory leak](https://github.com/arikis/Overdrive/pull/7) fixed. I would be happy to help in any way I can.

**Comment by arikis** [comment]
Hi @biocross, I wanted to release a `0.3` for some time now, but I've been putting in of due to some new features I want to introduce. But, I decided to put those new features in some next version. 

Version `0.3` will be released today then :)

**Comment by biocross** [comment]
Really great to hear! Thanks a lot :D

**Comment by biocross** [comment]
Hey @arikis ,

Just a reminder, looks like you didn't push 0.3 to the master [cocoapods specs repo](https://github.com/CocoaPods/Specs/tree/master/Specs/4/d/a/Overdrive).

**Comment by arikis** [comment]
Pushing it at the moment, updating pods always take some time :)

**Comment by biocross** [comment]
:)

**Comment by arikis** [comment]
Should be up now.

**Comment by biocross** [comment]
Got it. Thanks.
