### ISSUE TITLE
`maxConcurrentTaskCount` is inaccessible for clients

### ISSUE THREAD

**Issue by hffmnn** [arikis/Overdrive#3]
**Overdrive version:** `0.2.0`

**Package manager:** `CocoaPods 1.1`

This snippet

```
let queue = TaskQueue()
queue.maxConcurrentTaskCount = 3
```

throws ```'maxConcurrentTaskCount' is inaccessible due to 'internal' protection level```. See #2  for a possible fix.

**Comment by arikis** [comment]
Fixed with #2.
Thanks.
