### ISSUE TITLE
How to cancel the tasks are running?

### ISSUE THREAD

**Issue by zxl777** [arikis/Overdrive#6]
I try 
`inquireQueue.tasks.cancel()`

But can not work ,The task always run to end.

**Comment by arikis** [comment]
You need to define how your task is cancelled by overriding `cancel()` method in your task subclass. That is because task queue doesn't have any idea about what your task does unless you specify it.

For example:

```swift
class NetworkTask: Task<Int> {
  let networkTask: URLSessionTask

  init(withRequest request: URLRequest) {
    networkTask = // Define task
  }

  override func run() {
    networkTask.resume()
  }

  override func cancel() { // Override this method
    networkTask.cancel()
    super.cancel()
  }
}
```
